export const bookSeedData = [
	{
		author: 'George Orwell',
		availability: true,
		genres: ['Dystopian', 'Sci-Fi'],
		isbn: '978-0451524935',
		price: 15.5,
		publisher: 'Secker & Warburg',
		title: '1984',
	},
	{
		author: 'Harper Lee',
		availability: true,
		genres: ['Fiction', 'Classic'],
		isbn: '978-0061120084',
		price: 12,
		publisher: 'J. B. Lippincott & Co.',
		title: 'To Kill a Mockingbird',
	},
	{
		author: 'F. Scott Fitzgerald',
		availability: false,
		genres: ['Fiction', 'Classic'],
		isbn: '978-0743273565',
		price: 10.25,
		publisher: "Charles Scribner's Sons",
		title: 'The Great Gatsby',
	},
	{
		author: 'Frank Herbert',
		availability: true,
		genres: ['Sci-Fi'],
		isbn: '978-0441013593',
		price: 18.75,
		publisher: 'Chilton Books',
		title: 'Dune',
	},
	{
		author: 'J.R.R. Tolkien',
		availability: true,
		genres: ['Fantasy'],
		isbn: '978-0618640157',
		price: 25.99,
		publisher: 'Allen & Unwin',
		title: 'The Lord of the Rings',
	},
	{
		author: 'Jane Austen',
		availability: true,
		genres: ['Romance', 'Classic'],
		isbn: '978-1503290563',
		price: 9.99,
		publisher: 'T. Egerton, Whitehall',
		title: 'Pride and Prejudice',
	},
	{
		author: 'J.R.R. Tolkien',
		availability: false,
		genres: ['Fantasy'],
		isbn: '978-0345339683',
		price: 14.99,
		publisher: 'Allen & Unwin',
		title: 'The Hobbit',
	},
	{
		author: 'Aldous Huxley',
		availability: true,
		genres: ['Dystopian', 'Sci-Fi'],
		isbn: '978-0060850524',
		price: 16,
		publisher: 'Chatto & Windus',
		title: 'Brave New World',
	},
	{
		author: 'J.D. Salinger',
		availability: true,
		genres: ['Fiction', 'Classic'],
		isbn: '978-0316769488',
		price: 11.5,
		publisher: 'Little, Brown and Company',
		title: 'The Catcher in the Rye',
	},
	{
		author: 'Ray Bradbury',
		availability: true,
		genres: ['Dystopian', 'Sci-Fi'],
		isbn: '978-1451673319',
		price: 13.25,
		publisher: 'Ballantine Books',
		title: 'Fahrenheit 451',
	},
	{
		author: 'Herman Melville',
		availability: true,
		genres: ['Adventure', 'Classic'],
		isbn: '978-1503280786',
		price: 14,
		publisher: 'Harper & Brothers',
		title: 'Moby-Dick',
	},
	{
		author: 'Leo Tolstoy',
		availability: true,
		genres: ['Historical Fiction', 'Classic'],
		isbn: '978-1420959238',
		price: 19.99,
		publisher: 'The Russian Messenger',
		title: 'War and Peace',
	},
	{
		author: 'Douglas Adams',
		availability: true,
		genres: ['Sci-Fi', 'Comedy'],
		isbn: '978-0345391803',
		price: 12.99,
		publisher: 'Pan Books',
		title: "The Hitchhiker's Guide to the Galaxy",
	},
	{
		author: 'C.S. Lewis',
		availability: true,
		genres: ['Fantasy', "Children's"],
		isbn: '978-0066238500',
		price: 22.5,
		publisher: 'Geoffrey Bles',
		title: 'The Chronicles of Narnia',
	},
	{
		author: 'Stephen King',
		availability: true,
		genres: ['Horror', 'Thriller'],
		isbn: '978-0385121675',
		price: 17,
		publisher: 'Doubleday',
		title: 'The Shining',
	},
	{
		author: 'Margaret Atwood',
		availability: true,
		genres: ['Dystopian', 'Fiction'],
		isbn: '978-0385490818',
		price: 15,
		publisher: 'McClelland and Stewart',
		title: "The Handmaid's Tale",
	},
	{
		author: 'Mary Shelley',
		availability: true,
		genres: ['Gothic', 'Sci-Fi', 'Horror'],
		isbn: '978-0486282114',
		price: 8.99,
		publisher: 'Lackington, Hughes, Harding, Mavor, & Jones',
		title: 'Frankenstein',
	},
	{
		author: 'Oscar Wilde',
		availability: true,
		genres: ['Gothic', 'Philosophical Fiction'],
		isbn: '978-0486278070',
		price: 9.5,
		publisher: "Lippincott's Monthly Magazine",
		title: 'The Picture of Dorian Gray',
	},
	{
		author: 'Bram Stoker',
		availability: true,
		genres: ['Gothic', 'Horror'],
		isbn: '978-0486411095',
		price: 7.99,
		publisher: 'Archibald Constable and Company',
		title: 'Dracula',
	},
	{
		author: 'Lewis Carroll',
		availability: true,
		genres: ['Fantasy', "Children's"],
		isbn: '978-1503222663',
		price: 10,
		publisher: 'Macmillan',
		title: "Alice's Adventures in Wonderland",
	},
	{
		author: 'Mark Twain',
		availability: true,
		genres: ['Adventure', 'Satire', 'Classic'],
		isbn: '978-0486280615',
		price: 8.5,
		publisher: 'Chatto & Windus',
		title: 'The Adventures of Huckleberry Finn',
	},
	{
		author: 'Miguel de Cervantes',
		availability: true,
		genres: ['Satire', 'Classic'],
		isbn: '978-0060934347',
		price: 20,
		publisher: 'Francisco de Robles',
		title: 'Don Quixote',
	},
	{
		author: 'Gabriel García Márquez',
		availability: true,
		genres: ['Magical Realism', 'Fiction'],
		isbn: '978-0060883287',
		price: 18,
		publisher: 'Harper & Row',
		title: 'One Hundred Years of Solitude',
	},
	{
		author: 'Paulo Coelho',
		availability: true,
		genres: ['Fantasy', 'Adventure'],
		isbn: '978-0062315007',
		price: 14.99,
		publisher: 'HarperCollins',
		title: 'The Alchemist',
	},
	{
		author: 'Cormac McCarthy',
		availability: true,
		genres: ['Post-Apocalyptic', 'Fiction'],
		isbn: '978-0307387899',
		price: 16,
		publisher: 'Alfred A. Knopf',
		title: 'The Road',
	},
	{
		author: 'Kurt Vonnegut',
		availability: true,
		genres: ['Sci-Fi', 'Satire', 'War'],
		isbn: '978-0385333849',
		price: 14,
		publisher: 'Delacorte',
		title: 'Slaughterhouse-Five',
	},
	{
		author: 'John Steinbeck',
		availability: true,
		genres: ['Fiction', 'Classic'],
		isbn: '978-0143039433',
		price: 17.5,
		publisher: 'The Viking Press',
		title: 'The Grapes of Wrath',
	},
	{
		author: 'Anthony Burgess',
		availability: true,
		genres: ['Dystopian', 'Sci-Fi'],
		isbn: '978-0393312836',
		price: 13,
		publisher: 'William Heinemann',
		title: 'A Clockwork Orange',
	},
	{
		author: 'Sylvia Plath',
		availability: true,
		genres: ['Fiction', 'Autobiographical'],
		isbn: '978-0060837020',
		price: 12.5,
		publisher: 'Heinemann',
		title: 'The Bell Jar',
	},
	{
		author: 'William Gibson',
		availability: true,
		genres: ['Sci-Fi', 'Cyberpunk'],
		isbn: '978-0441569595',
		price: 15.99,
		publisher: 'Ace Books',
		title: 'Neuromancer',
	},
];
